pull_request_rules:
  - name: Merge PRs from Scala Steward that pass validation
    conditions:
      - status-success=Travis CI - Pull Request
      - author=scala-steward
    actions:
      merge:
        method: merge
        
  - name: Delete the PR branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}