language: scala

jobs:
  include:
    - stage: check
      script: sbt scalafmtCheck || { echo "[error] Unformatted code found. Please run 'Test/compile' and commit the reformatted code."; false; }
      name: "Code style check (fixed with `sbt Test/compile`)"
    - script: sbt scalafmtSbtCheck || { echo "[error] Unformatted sbt code found. Please run 'scalafmtSbt' and commit the reformatted code."; false; }
      name: "Build code style check (fixed with `sbt scalafmtSbt`)"

    - stage: test
      script: sbt test
      name: "Run all tests"

    - stage: publish
      script: sbt publish bintraySyncMavenCentral
      name: "Publish artifacts to Maven Central"
    
    - stage: publish-snapshot
      script: sbt publish
      name: "Publish artifacts to Bintray snapshot repository"

stages:
  # runs on master commits and PRs
  - name: check
    if: NOT tag =~ ^v

  # runs on master commits and PRs
  - name: test
    if: NOT tag =~ ^v

  # runs on main repo version-tagged commits
  - name: publish
    if: repo = 2m/ciris-hocon AND tag =~ ^v
  
  # runs on main repo master commits
  - name: publish-snapshot
    if: repo = 2m/ciris-hocon AND ( branch = master AND type = push )

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
  timeout: 900

env:
  global:
    - BINTRAY_USER=2m
    # encrypt with: travis encrypt BINTRAY_PASS=...
    - secure: "kTODv5Ve0jyuVa0HdwosE9bV95nJkZvyEH5/cQCZrX5gIVNj18p1vIRfwLUoxxoKvAP0pSwK4fsDFv8pZKxogOh+gCJw/fmroJ1vAyH5sSETKndPx9pdLgvuusAwlXCanHJewihVOHTL3qLP/8X+hrtDoZCyjLRPqvfd4H8dymFcCTb6u2HmIoR4+czL3/jcLJONpj59KWHlI2OyfNoWtVerwMy5Ic+swSOnof/A4uiwVvMEcJkr7fVOBa/jVtXGMfV8FClbMYAX31dvw0wSA9+ienrkUiXUzPfwW6lR2Ap8NF6mMzhm9W1Io9fx6hyVXO8asRzgYT88pO4C+vDaynXdaACfCFRU+jV6Zvd4UTPOfwPJ4oiT+159II2tGQ6aLTGv0czp8N8wtQsa20y8JFf1O9pxQAcXkTEC3qmOVC0VWMHrvtedskYZYS9yKikb0Kc+nz+/v1el/RO8jCchwscv4pvHroLx8c4a8ug6P28KDBH+f4UC5GOcalVzhBnZF+wYYaHuuc7HVFyVaarEEZFOn+J051VFn1zcqlwqRs8vVLL5duf9udFaysYbX4RbQaneAY7SBiYGmkj4ciltFlDqcGGrCPgZPdZxeK1wSji1+eKNQmVZmdVW7bRUA6JIjQ8gjje5l2CsJjd7eYW/P5Syt01JfaIDFglekgFxAnM="
    # encrypt with: travis encrypt SONA_USER=...
    - secure: "aR+FLixZXBmEXkE2c3GrkSvPWlVwkuRW3tOGXsK61raqRXEm1D0PE9rRNv1Ewd35QRxcNDTJBaTCSp2vIPJEIdTuB6XSEqKC6pj64Gv9cAwpBvbcxNvvHCVHi9o5AraW01CTh9EcExd3GbxAJzNf9VAjmNx32WrGFL/MRMLix5K93d7GCJrfcRAhTlNxQmX38Ag8r37i+4ndGi0W+H2EdA4ZZute3mcDDiywm0ZnraKQB0nWN4v6xEKIqL/vKzSh1VwOBMAuzB/XCxG9HarBMf3mTniCVoTdjTX66WrQcGl5WV4uebHwT4l9/EwMZhGfz91LAdcB1HUQp4990/yXOKcuFHAM/U0juRV1a59GU90wN53ceCWJsajjTlBikSeYrARhrmUA60La3vNf8xlyjpyGfgvSr4SZTjI0dn8gKksA+oakJBYpP2I4B7KFgDPWEOCZDlHqI1UlfsYmioUmkiXE3mQ6mYTrw+4r/oAsYmZYsyMSnoY5HorxxCUftSJtmsFyWBqZLqEzkLbrmRjgBjchsC2SPe67w6G2AGan2dIeuQ5bgNXexxKKaxcOpIe2hMcgvYxvw/3s0ELErheQTn51y9mB3J0Pd+gMAy/ycjVirAvHNCFWMAjVMxVuwSqNhkWWvH7Eu5JT3OlV7zVVfzZGII11qUZs4lyI/08F+ZY="
    # encrypt with: travis encrypt SONA_PASS=...
    - secure: "TdlQhi5QWL777YFa7bXRb2lvB3CRNVgajGI4jSx/pXDAviClW3iv3/w+GVsNbxOl41VBi/PJSjqeJj4+tUS3RCTo8jbYiPwTKsv7WgTnmL1KUkXbPSe0i8zLNvl9UELYPhROb59QIw+wV9Kp62fuBysJpbL39JPbGqkdRaTuvPN0biEH4FJZxHyiXMZ+cY5P72Wm0HBWKlev3KAUKCyzrC1+1/7sMznC5lIc2pytZCRULokeRWY1VTn/PL1yYjXu4+vBtU/vlF8jeR3Q8G3zY3h6iidu0M89zgBy5pul4Oh5RloXOExBMkhk0Uqbkzlk1LN1mEEklbyEmgjvmxBUL2af4uPmELd0QuyWvWn0t01IUmoEPYK4wuKW6sHq63G0FgbdG5VCkUM1w/kvq1dVRdkIzW/H8ZG4CxmeYmMHWflI3KldGqlNw0mUkf2QxMDwBfiPUC/NFWKuZBq79B99mJ/96Z/kmggog3SC07jfSFWm8n7mnj76ET+g9zctrQlEMDlp456Y88hl+EHWkKwVylAXpITiYs3GlLaPFYyjyRVsb5aj+/XkSr6wQpjlL0guVA21PZmwnPQmYtjqrHZ/qu8KNfniyWgDScXVcqmvR4rT6rq/NVUy+T3ne05ENJwHoLOxjU900BpISOpBh4d2+QeML2+sZxgATJ6vh73Dhoc="
