language: scala

jobs:
  include:
    - stage: check
      script: sbt scalafmtCheck || { echo "[error] Unformatted code found. Please run 'Test/compile' and commit the reformatted code."; false; }
      name: "Code style check (fixed with `sbt Test/compile`)"
    - script: sbt scalafmtSbtCheck || { echo "[error] Unformatted sbt code found. Please run 'scalafmtSbt' and commit the reformatted code."; false; }
      name: "Build code style check (fixed with `sbt scalafmtSbt`)"

    - stage: test
      script: sbt test
      name: "Run all tests"

    - stage: publish
      script: sbt publish bintraySyncMavenCentral
      name: "Publish artifacts to Maven Central"

    - stage: publish-snapshot
      script: sbt publish
      name: "Publish artifacts to Bintray snapshot repository"

stages:
  # runs on master commits and PRs
  - name: check
    if: NOT tag =~ ^v

  # runs on master commits and PRs
  - name: test
    if: NOT tag =~ ^v

  # runs on main repo version-tagged commits
  - name: publish
    if: repo = 2m/ciris-hocon AND tag =~ ^v

  # runs on main repo master commits
  - name: publish-snapshot
    if: repo = 2m/ciris-hocon AND ( branch = master AND type = push )

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
  timeout: 900

env:
  global:
    - BINTRAY_USER=2m
    # encrypt with: travis encrypt BINTRAY_PASS=...
    - secure: "kTODv5Ve0jyuVa0HdwosE9bV95nJkZvyEH5/cQCZrX5gIVNj18p1vIRfwLUoxxoKvAP0pSwK4fsDFv8pZKxogOh+gCJw/fmroJ1vAyH5sSETKndPx9pdLgvuusAwlXCanHJewihVOHTL3qLP/8X+hrtDoZCyjLRPqvfd4H8dymFcCTb6u2HmIoR4+czL3/jcLJONpj59KWHlI2OyfNoWtVerwMy5Ic+swSOnof/A4uiwVvMEcJkr7fVOBa/jVtXGMfV8FClbMYAX31dvw0wSA9+ienrkUiXUzPfwW6lR2Ap8NF6mMzhm9W1Io9fx6hyVXO8asRzgYT88pO4C+vDaynXdaACfCFRU+jV6Zvd4UTPOfwPJ4oiT+159II2tGQ6aLTGv0czp8N8wtQsa20y8JFf1O9pxQAcXkTEC3qmOVC0VWMHrvtedskYZYS9yKikb0Kc+nz+/v1el/RO8jCchwscv4pvHroLx8c4a8ug6P28KDBH+f4UC5GOcalVzhBnZF+wYYaHuuc7HVFyVaarEEZFOn+J051VFn1zcqlwqRs8vVLL5duf9udFaysYbX4RbQaneAY7SBiYGmkj4ciltFlDqcGGrCPgZPdZxeK1wSji1+eKNQmVZmdVW7bRUA6JIjQ8gjje5l2CsJjd7eYW/P5Syt01JfaIDFglekgFxAnM="
    # encrypt with: travis encrypt SONA_USER=...
    - secure: "Pk8jKZGwq0z5VtOGAW+V0dp1M3cUg7kDyY07rSw9GAkzQUmlBfofXBk52VQ0kOZ+cO7wfobrV4Rbi4q1nRgGoxpBslkjsoQyBZmIFkSiDZLeQAESe4aLoTwTbO3IaimIsvDIu+m4S5Z0FE8YMZFOr1tvFjycT8MZKh3LuJnC2TY7K95y0lofumi3cFcdPElKsSyw0N/4gRuA3BvMib4CSAoM+tgRbZb03mVd32YjJNuCPtWI7o/BAwLHTboYA/Gur0FUw97G/BND7cxvBQp4vItGaL53qbbpgv2jeXbtRSrthwD5GI3lgxA6zBvWeI/rd4EwHg9ViK8AlFH1P6WcW0LcfZdXKaI5acGNe6+SnE2I9s+nt/yc4KYj6QczlCWyhQKBciQ9MgA6U2hWUVCkPTXQYzvYvI6LRQ/HqcRUWVDOl5V7E9EGI1YXwu5kUrJi4GXWlEXf10Ix46QAeeIDHpNR/4nb3b3OriemMhfYgJcxkKAVZIAdcpFzsgXs5BE2+mHAIVyXMEqOcfrRbYMm6wtt0zirBiq37JWQwRqi2acTFY6D0xtEcKKEzKxXgsXYEGfmczp1W+S2LGCJn3DyNHlavWWK0ahz4v3fDkSXVCFTR5dU0tDG6NZmU+d90FQxyPPRQEHG3jGQOFTV4BTPrWM0TkxskwMG5nRaMUlgm0c="
    # encrypt with: travis encrypt SONA_PASS=...
    - secure: "gY0Gf7RXbMFq4aP3HEae4qya8zYRAK+D33q+6kpppz87HE6snWt6aItgaCMVT8OcQkJyzg9AwiDBpL76CrcoAEISPlD2QATv6sZYwH4Gudq8M9AIXFYlQOkNlmhuXGSeRw3H+bXSYSaGJEGa/J7HRfp4zlngy5y4w/pZkMopvYbv+98DMShLRusAsd6YR67sFPR+4dNyd8oMD/yUFKAxpYt6o8QYOQwT1EFv9fuTIgiIpQD6VjGwt2QyarfUgJsT2oW+DF4V6X2dhL8JE9UdOdbROEV8Vbfxi1vzCgk18JBQgJmWe9c9OLfn6v40fyqSwsPzxXPoILI/cw61n/DxcwYedfXORVwmfGO92tnacwJeCCMx6gqa2sMKa91WHKHPZufs0BeHstIyWMk5Dj9yef69MP8TJfV3zej8YIcM3trOCTdvnNohDzb5fRLEW2UnqnK1GrqB2jkJRoaAqwhj0R758g5FU1MsBQ1a9V68qZ8/nRPvziXBll01f4+pfx59wsGJmvIw6aS3UIUxiUGtJJUUcIjU0E4ONVnIcCwAeiD4ndxTagLCR7O3MtFX5dinCKeO90IIvMmQtdTAFK7882Fx1Xjas3WZlGDg70Gr2KrMPqBkAaqvSSQ7zCOBsw5fCG7Mxj7kgocCSlHr78TeR8UGtNhduwRy54bxiCgewzE="
