addSbtPlugin("com.dwijnand"              % "sbt-dynver"       % "4.1.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"     % "2.5.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"     % "0.11.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"     % "0.4.2")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"       % "5.9.0")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"   % "1.5.11")
addSbtPlugin("io.github.zamblauskas"     % "sbt-examplestest" % "0.3.0")
