addSbtPlugin("com.dwijnand"          % "sbt-dynver"       % "4.1.1")
addSbtPlugin("org.scalameta"         % "sbt-scalafmt"     % "2.5.2")
addSbtPlugin("org.typelevel"         % "sbt-tpolecat"     % "0.5.0")
addSbtPlugin("de.heikoseeberger"     % "sbt-header"       % "5.9.0")
addSbtPlugin("com.github.sbt"        % "sbt-ci-release"   % "1.5.12")
addSbtPlugin("io.github.zamblauskas" % "sbt-examplestest" % "0.3.0")
